### ISSUE TITLE
Start/stopp shortcuts

### ISSUE THREAD

**Issue by HannaLindgren** [stts-se/tillstudpub#43]

**Comment by HannaLindgren** [comment]
Funkar det inte?

**Comment by NikolajLindberg** [comment]
Alt-s in Firefox drops down the browsing history!

What a pity --- I liked Alt-s.

(But the recording starts as well.)

**Comment by HannaLindgren** [comment]
It works if you use it in fullscreen (F11).......

But I changed the shortcut to Ctrl-Y instead for now.
