### ISSUE TITLE
server: Protect "latest.raw" with mutex?

### ISSUE THREAD

**Issue by NikolajLindberg** [stts-se/tillstudpub#5]
If two of more clients use the server simultaneously, the "latest.raw" file might end up corrupted?

First step could be to protect the file with a mutex lock, but the correct solution is probably to separate clients, either using a file prefix or by creating sub directories unique to each client.
 
Probably this becomes a non-issue after improving how the files are stored on the server.

**Comment by HannaLindgren** [comment]
Fixed for .raw and .json files, but it could also be that in future versions we don't save "latest" files (this is good for developing but maybe not useful when stable?)
